### ISSUE TITLE
MACOS: samples do not run after successful npm install

### ISSUE THREAD

**Issue by eighteight** [Eyevinn/node-srt#19]
I used brew to install srt and openssl. Then

```
OPENSSL_ROOT_DIR=/usr/local/opt/openssl npm install --save @eyevinn/srt
```
to successfully install node-srt.

However classic examples such as (or any samples and scripts in the ...test folder)

```
const fs = require('fs');
const dest = fs.createWriteStream('./output');
const { SRTReadStream } = require('@eyevinn/srt');
const srt = new SRTReadStream('0.0.0.0', 1234);
srt.listen(readStream => {
    console.log("Client connected");
    readStream.pipe(dest);
});
srt.on('end', () => {
    console.log("Client disconnected");
});
console.log("Waiting for client to connect");
```

Do not start with the error
```
const TimeoutMs = DEFAULT_PROMISE_TIMEOUT_MS;
        ^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/eigh_io/srt-client-server/node_modules/@eyevinn/srt/index.js:2:22)
```

**Comment by eighteight** [comment]
OK, it turned out I had outdated node. After upgrading to v15.11.0 it all works.
