### ISSUE TITLE
how to prevent Connection was broken? 

### ISSUE THREAD

**Issue by CassianoDev** [Eyevinn/node-srt#27]
I have a code I want to run to wait for connection:

```
const { SRTReadStream } = require('@eyevinn/srt');
const srt = new SRTReadStream('0.0.0.0', 1235);
srt.listen(readStream => {
  console.log("Client connected");
  readStream.on("data", (e) => {
    console.log(e)
  })
});
srt.on('end', () => {
  console.log("Client disconnected");
});


console.log("Waiting for client to connect");
```

I use ffmpeg to send:
`ffmpeg -async 1 -vsync 1 -re -i '/home/iam/Videos/1.mp4' -c copy -t 00:00:05 -f mpegts srt://127.0.0.1:1235?pkt_size=1316`

But even with the treatment `'srt.on('end''`, when disconnecting the FFMPEG, this error appears:
```
//home/iam/Documents/pipetest/node_modules/@eyevinn/srt/src/srt-stream-readable.js:136
      const buffer = this.srt.read(this.fd, bytes);
                              ^

Error: srt_recvmsg: Connection was broken
    at SRTReadStream._readSocketAndPush (/home/iam/Documents/pipetest/node_modules/@eyevinn/srt/src/srt-stream-readable.js:136:31)
    at SRTReadStream._read (/home/iam/Documents/pipetest/node_modules/@eyevinn/srt/src/srt-stream-readable.js:171:10)
    at SRTReadStream.Readable.read (node:internal/streams/readable:483:10)
    at flow (node:internal/streams/readable:1005:34)
    at resume_ (node:internal/streams/readable:986:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
I want the connection to be keep wait infinite,  that I can connect and stop ffmpeg at any time,That when disconnecting it wait for new socket connect and wait for a new entry to continue.

Can you help me?

**Comment by peykens** [comment]
Did you get this resolved ?

**Comment by CassianoDev** [comment]
> Did you get this resolved ?
Unfortunately not!

**Comment by CassianoDev** [comment]
> Did you get this resolved ?

Unfortunately not!

**Comment by CassianoDev** [comment]
I migrated to [srtgo](https://github.com/Haivision/srtgo) (Go language project)

**Comment by tigercoxgithub** [comment]
problem persists
